version: "3"

services:
  samba:
    container_name: "samba"
    hostname: "river"
    image: dperson/samba
    environment:
      - USERID=65534
      - GROUPID=65534
    volumes:
      - /export/share:/mnt/share
      - samba-var-lib-samba:/var/lib/samba
      - samba-var-cache-samba:/var/cache/samba
      - samba-var-log-samba:/var/log/samba
      - samba-etc:/etc
      - samba-run-samba:/run/samba
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
      - "137:137/udp"
      - "138:138/udp"
    command: samba.sh -n -s "share;/mnt/share;yes;no;yes;all;none"
    restart: unless-stopped

volumes:
  samba-var-lib-samba:
  samba-var-cache-samba:
  samba-var-log-samba:
  samba-etc:
  samba-run-samba:
