version: "3"

services:
  coredns:
    container_name: "coredns"
    image: coredns/coredns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped
    command: -conf /config/Corefile
    volumes:
      - ./coredns-config:/config/
    networks:
      default:
        ipv4_address: 10.1.0.2

  pihole:
    container_name: "pihole"
    image: pihole/pihole:latest
    environment:
      - DNS1=10.1.0.5#5054
      - DNS2=1.1.1.1
      - IPv6=false
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=
    volumes:
      - pihole-etc-pihole:/etc/pihole/
      - pihole-etc-dnsmasq.d:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:pihole.services.dubs.zone;AddPrefix:/admin"
    networks:
      default:
        ipv4_address: 10.1.0.4
      web:

  cloudflared:
    container_name: "cloudflared"
    image: visibilityspots/cloudflared:latest
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.1.0.5

volumes:
  pihole-etc-pihole:
  pihole-etc-dnsmasq.d:

networks:
  default:
    ipam:
      config:
        - subnet: 10.1.0.0/29
  web:
    external: true
