version: "3"

services:
  cam:
    container_name: cam
    image: transcode:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:cam.services.dubs.zone"
    networks:
      web:

networks:
  web:
    external: true
