- id: '6'
  alias: Garage Light Timeout
  trigger:
  - platform: state
    entity_id: switch.ge_quick_fit_smart_in_wall_paddle_switch_17
    from: 'off'
    to: 'on'
    for:
      minutes: 10
  action:
  - service: homeassistant.turn_off
    data: {}
    target:
      device_id: 9213e3479deec8523d457b0c816cadf3
  initial_state: 'on'
- id: '7'
  alias: Downstairs Bathroom Fan Timeout
  trigger:
  - platform: state
    entity_id: switch.ge_quick_fit_smart_in_wall_paddle_switch_15
    from: 'on'
    to: 'off'
    for:
      minutes: 10
  condition:
  - condition: state
    entity_id: switch.in_wall_paddle_switch_12
    state: 'on'
  action:
  - service: homeassistant.turn_off
    data: {}
    target:
      device_id: 2e4c762e8e0f3fd4c3c319ba178acffc
  initial_state: 'on'
- id: '10'
  alias: Kitchen Light Refresh
  trigger:
  - platform: state
    entity_id: switch.ge_quick_fit_smart_in_wall_paddle_switch_13
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 4
      milliseconds: 0
  - service: zwave_js.refresh_value
    data:
      entity_id: switch.ge_quick_fit_smart_in_wall_paddle_switch_12
  initial_state: 'on'
- id: '11'
  alias: Master Bathroom Fan Timeout
  trigger:
  - platform: state
    entity_id: light.in_wall_dimmer_switch_3
    from: 'on'
    to: 'off'
    for:
      minutes: 10
  - platform: state
    entity_id: light.in_wall_dimmer_switch_2
    from: 'on'
    to: 'off'
    for:
      minutes: 10
  condition:
  - condition: state
    entity_id: light.in_wall_dimmer_switch_2
    state: 'off'
  - condition: state
    entity_id: light.in_wall_dimmer_switch_3
    state: 'off'
  - condition: state
    entity_id: switch.ge_quick_fit_smart_in_wall_paddle_switch_2
    state: 'on'
  action:
  - service: homeassistant.turn_off
    data: {}
    target:
      device_id: ca2c4f25dc4086f949de84721e360111
  initial_state: 'on'
- id: '12'
  alias: Master Water Closet Fan Timeout
  trigger:
  - platform: state
    entity_id: light.in_wall_dimmer_switch_5
    from: 'on'
    to: 'off'
    for:
      minutes: 10
  condition:
  - condition: state
    entity_id: switch.in_wall_paddle_switch_3
    state: 'on'
  action:
  - service: homeassistant.turn_off
    data: {}
    target:
      device_id: d20e6e73656af951d927c688ea8911a0
  initial_state: 'on'
- id: '13'
  alias: Master Bathroom Light Refresh
  trigger:
  - platform: state
    entity_id: light.in_wall_dimmer_switch_3
  action:
  - delay: 00:00:02
  - service: zwave_js.refresh_value
    data:
      entity_id: light.in_wall_dimmer_switch_2
  - service: zwave_js.refresh_value
    data:
      entity_id: light.in_wall_dimmer_switch_4
  initial_state: 'on'
- id: '14'
  alias: Art Room Closet Door Open
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.art_room_closet_door
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_boolean.automatic_art_room_closet_lights
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.art_room_closet_door
    state: 'on'
  - condition: state
    entity_id: input_boolean.automatic_art_room_closet_lights
    state: 'on'
  - condition: state
    entity_id: switch.art_room_closet_light
    state: 'off'
  action:
    service: homeassistant.turn_on
    data:
      entity_id: switch.art_room_closet_light
- id: '15'
  alias: Art Room Closet Door Closed
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.art_room_closet_door
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_boolean.automatic_art_room_closet_lights
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.art_room_closet_door
    state: 'off'
  - condition: state
    entity_id: input_boolean.automatic_art_room_closet_lights
    state: 'on'
  - condition: state
    entity_id: switch.art_room_closet_light
    state: 'on'
  action:
    service: homeassistant.turn_off
    data:
      entity_id: switch.art_room_closet_light
- id: '16'
  alias: Outdoor Lights On
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data: {}
    service: homeassistant.turn_on
    target:
      device_id:
      - c0657c4e8af9cbf8773345ada686f615
      - e413c70e8c09002f20cb8bb6476ade66
      - 334df6d5c4cf28068a53195474fe9037
  initial_state: 'on'
- id: '17'
  alias: Outdoor Lights Off
  trigger:
  - event: sunrise
    offset: -00:20:00
    platform: sun
  action:
  - data: {}
    service: homeassistant.turn_off
    target:
      device_id:
      - c0657c4e8af9cbf8773345ada686f615
      - 334df6d5c4cf28068a53195474fe9037
      - e413c70e8c09002f20cb8bb6476ade66
  initial_state: 'on'
- id: '19'
  alias: Upstairs Bathroom Fan Timeout
  trigger:
  - platform: state
    entity_id: switch.ge_quick_fit_smart_in_wall_paddle_switch_3
    from: 'on'
    to: 'off'
    for:
      minutes: 10
  condition:
  - condition: state
    entity_id: switch.ge_quick_fit_smart_in_wall_paddle_switch_4
    state: 'on'
  action:
  - service: homeassistant.turn_off
    data: {}
    target:
      device_id: 00d8aef3ffa9d0c86cd6d895600efb93
  initial_state: 'on'
- id: '20'
  alias: Upstairs Water Closet Fan Timeout
  trigger:
  - platform: state
    entity_id: switch.upstairs_water_closet_light_switch
    from: 'on'
    to: 'off'
    for:
      minutes: 10
  condition:
  - condition: state
    entity_id: switch.ge_quick_fit_smart_in_wall_paddle_switch_6
    state: 'on'
  action:
  - service: homeassistant.turn_off
    data: {}
    target:
      device_id: 121f40b353820e0b9e5a4394b009baad
  initial_state: 'on'
